export const ERROR_STATUS = {
  BAD_REQUEST: 400,
  FORBIDDEN: 403,
  GENERIC_ERROR: 500,
  NOT_FOUND: 404,
  UNAUTHORIZED: 401,
  UNPROCESSABLE: 422,
};
export const ERROR_TYPE = {
  GENERIC_ERROR: 'GENERIC_ERROR',
  VALIDATION_FAILED: 'VALIDATION_ERROR',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
};
