version: '3'

services:
    discord:
        container_name: discord
        build:
            context: .
            dockerfile: ./discord/Dockerfile
            target: base
        volumes:
            - ./discord/src:/home/discord/app/src
        env_file:
            - ./discord/.env
        command: npm run --prefix ./discord dev
