version: '3.9'

services:
  # discord:
  #   container_name: discord
  #   build:
  #     context: .
  #     dockerfile: ./discord/Dockerfile
  #     target: base
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   env_file:
  #     - ./discord/.env
  #   command: npm run --prefix ./discord dev
  # server:
  #   container_name: server
  #   build:
  #     context: .
  #     dockerfile: ./server/Dockerfile
  #     target: base
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   env_file:
  #     - ./server/.env
  #   command: npm run --prefix ./server dev
  db:
    container_name: db
    image: mysql:8.0.33
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=discord_bot_db
      - MYSQL_ROOT_PASSWORD=password
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root -ppassword
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

volumes:
  db-data:
