version: '3'

services:
    discord:
        container_name: discord
        build:
            context: .
            dockerfile: ./discord/Dockerfile
            target: base
        volumes:
            - ./discord/src:/home/discord/app/src
        env_file:
            - ./discord/.env
        command: npm run --prefix ./discord dev
    db:
        container_name: db
        image: mysql:8.0.33
        ports:
            - 3306:3306
        volumes:
            - db-data:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=discord-bot-db
            - MYSQL_ROOT_PASSWORD=password

volumes:
    db-data:
